# Cliping A tiff File

In [1]:
import rasterio
import rasterio.mask
import fiona
import matplotlib.pyplot as plt
import numpy as np
import os 
import pandas as pd

In [2]:
with fiona.open("../DATASETS/AusPlots_Location/AusPlots_Published_Corner_Points_20240701/Derived_Boundary_Polygons/AusPlots_Polygons_from_Published_Plots.shp", "r") as shapefile:
    shapes = [feature["geometry"] for feature in shapefile]
    shapes_name = [properties["properties"]['st_lct_'] for properties in shapefile]

In [3]:
data_file_path = 'D:/Krish_New/SLGA/'
#data_file_path = 'C:/Users/krish/Desktop/Test/'
slga_datafiles = os.listdir(data_file_path) # list all datafiles 
slga_datafiles.sort()

In [4]:
slga_datafiles

['AVP_000_005_EV_N_P_AU_TRN_N_20220826.tif',
 'AVP_005_015_EV_N_P_AU_TRN_N_20220826.tif',
 'AVP_015_030_EV_N_P_AU_TRN_N_20220826.tif',
 'AVP_030_060_EV_N_P_AU_TRN_N_20220826.tif',
 'AVP_060_100_EV_N_P_AU_TRN_N_20220826.tif',
 'AVP_100_200_EV_N_P_AU_TRN_N_20220826.tif',
 'CLY_000_005_EV_N_P_AU_TRN_N_20210902.tif',
 'CLY_005_015_EV_N_P_AU_TRN_N_20210902.tif',
 'CLY_015_030_EV_N_P_AU_TRN_N_20210902.tif',
 'CLY_030_060_EV_N_P_AU_TRN_N_20210902.tif',
 'CLY_060_100_EV_N_P_AU_TRN_N_20210902.tif',
 'CLY_100_200_EV_N_P_AU_TRN_N_20210902.tif',
 'DER_000_999_EV_N_P_AU_NAT_C_20150601.tif',
 'NTO_000_005_EV_N_P_AU_NAT_C_20140801.tif',
 'NTO_005_015_EV_N_P_AU_NAT_C_20140801.tif',
 'NTO_015_030_EV_N_P_AU_NAT_C_20140801.tif',
 'NTO_030_060_EV_N_P_AU_NAT_C_20140801.tif',
 'NTO_060_100_EV_N_P_AU_NAT_C_20140801.tif',
 'NTO_100_200_EV_N_P_AU_NAT_C_20140801.tif',
 'PHW_005_015_EV_N_P_AU_TRN_N_20220520.tif',
 'PHW_015_030_EV_N_P_AU_TRN_N_20220520.tif',
 'PHW_030_060_EV_N_P_AU_TRN_N_20220520.tif',
 'PHW_060_100_EV_N_P_AU_TRN_N_20220520.tif',
 'PHW_100_200_EV_N_P_AU_TRN_N_20220520.tif',
 'PTO_000_005_EV_N_P_AU_NAT_C_20140801.tif',
 'PTO_005_015_EV_N_P_AU_NAT_C_20140801.tif',
 'PTO_015_030_EV_N_P_AU_NAT_C_20140801.tif',
 'PTO_030_060_EV_N_P_AU_NAT_C_20140801.tif',
 'PTO_060_100_EV_N_P_AU_NAT_C_20140801.tif',
 'PTO_100_200_EV_N_P_AU_NAT_C_20140801.tif',
 'SLT_000_005_EV_N_P_AU_TRN_N_20210902.tif',
 'SLT_005_015_EV_N_P_AU_TRN_N_20210902.tif',
 'SLT_030_060_EV_N_P_AU_TRN_N_20210902.tif',
 'SLT_060_100_EV_N_P_AU_TRN_N_20210902.tif',
 'SLT_100_200_EV_N_P_AU_TRN_N_20210902.tif',
 'pHc_000_005_EV_N_P_AU_NAT_C_20140801.tif',
 'pHc_005_015_EV_N_P_AU_NAT_C_20140801.tif',
 'pHc_015_030_EV_N_P_AU_NAT_C_20140801.tif',
 'pHc_030_060_EV_N_P_AU_NAT_C_20140801.tif',
 'pHc_060_100_EV_N_P_AU_NAT_C_20140801.tif',
 'pHc_100_200_EV_N_P_AU_NAT_C_20140801.tif']

In [5]:
column_names = [] # create user_friendly column names 
for i in slga_datafiles:
    split_words = i.split('_')[:3]
    column_names.append('_'.join(split_words))
column_names

['AVP_000_005',
 'AVP_005_015',
 'AVP_015_030',
 'AVP_030_060',
 'AVP_060_100',
 'AVP_100_200',
 'CLY_000_005',
 'CLY_005_015',
 'CLY_015_030',
 'CLY_030_060',
 'CLY_060_100',
 'CLY_100_200',
 'DER_000_999',
 'NTO_000_005',
 'NTO_005_015',
 'NTO_015_030',
 'NTO_030_060',
 'NTO_060_100',
 'NTO_100_200',
 'PHW_005_015',
 'PHW_015_030',
 'PHW_030_060',
 'PHW_060_100',
 'PHW_100_200',
 'PTO_000_005',
 'PTO_005_015',
 'PTO_015_030',
 'PTO_030_060',
 'PTO_060_100',
 'PTO_100_200',
 'SLT_000_005',
 'SLT_005_015',
 'SLT_030_060',
 'SLT_060_100',
 'SLT_100_200',
 'pHc_000_005',
 'pHc_005_015',
 'pHc_015_030',
 'pHc_030_060',
 'pHc_060_100',
 'pHc_100_200']

In [6]:
site_slga_data = pd.DataFrame(columns = column_names, index = shapes_name)
site_slga_data.head()

,AVP_000_005,AVP_005_015,AVP_015_030,AVP_030_060,AVP_060_100,AVP_100_200,CLY_000_005,CLY_005_015,CLY_015_030,CLY_030_060,...,SLT_005_015,SLT_030_060,SLT_060_100,SLT_100_200,pHc_000_005,pHc_005_015,pHc_015_030,pHc_030_060,pHc_060_100,pHc_100_200
NSABBS0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NSABBS0002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NSABBS0003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NSABBS0004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NSABBS0005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

```python


for col_idx, df in enumerate(slga_datafiles):
    
    variable_mean = []
    file_path = data_file_path+df

    with rasterio.open(file_path) as src:

        for i, shape in enumerate(shapes):
            shape = [shape] # shape has to be in a list 
            shape_name = shapes_name[i] # reference the name of  the site 

            out_image, out_transform = rasterio.mask.mask(src, shape, crop=True) # perform masking 
            
            # out_meta = src.meta # update meta data of masked content 

            # out_meta.update({"driver": "GTiff",
            #              "height": out_image.shape[1],
            #              "width": out_image.shape[2],
            #              "transform": out_transform})

            image_mean = np.nanmean(out_image)
            variable_mean.append(image_mean)
        
    site_slga_data[column_names[col_idx]] = variable_mean

        #with rasterio.open(f"../DATASETS/Soils_and_Landscape_Grid_of_Australia/Output/{file_name}/{shape_name}_{file_name}.tif" , "w", **out_meta) as dest:
        #    dest.write(out_image)
```

In [7]:
for col_idx, df in enumerate(slga_datafiles):
    
    variable_mean = []
    file_path = data_file_path+df
    
    split_words = df.split('_')[:3]
    column_name = '_'.join(split_words)

    with rasterio.open(file_path) as src:
        print(src)

        for i, shape in enumerate(shapes):

            shape = [shape] # shape has to be in a list 
            shape_name = shapes_name[i] # reference the name of  the site 
            #print(shape_name)

            out_image, out_transform = rasterio.mask.mask(src, shape, all_touched = True, crop=True, nodata = -999999) # perform masking
            out_image_filter = out_image[out_image != -999999]
            image_mean = np.nanmean(out_image_filter)       
            variable_mean.append(image_mean)
        
    site_slga_data[column_name] = variable_mean

<open DatasetReader name='D:/Krish_New/SLGA/AVP_000_005_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/AVP_005_015_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/AVP_015_030_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/AVP_030_060_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/AVP_060_100_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/AVP_100_200_EV_N_P_AU_TRN_N_20220826.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_000_005_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_005_015_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_015_030_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_030_060_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_060_100_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/CLY_100_200_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/DER_000_999_EV_N_P_AU_NAT_C_20150601.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_000_005_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_005_015_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_015_030_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_030_060_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_060_100_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/NTO_100_200_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PHW_005_015_EV_N_P_AU_TRN_N_20220520.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PHW_015_030_EV_N_P_AU_TRN_N_20220520.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PHW_030_060_EV_N_P_AU_TRN_N_20220520.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PHW_060_100_EV_N_P_AU_TRN_N_20220520.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PHW_100_200_EV_N_P_AU_TRN_N_20220520.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_000_005_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_005_015_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_015_030_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_030_060_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_060_100_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/PTO_100_200_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/SLT_000_005_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/SLT_005_015_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/SLT_030_060_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/SLT_060_100_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/SLT_100_200_EV_N_P_AU_TRN_N_20210902.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_000_005_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_005_015_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_015_030_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_030_060_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_060_100_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>
<open DatasetReader name='D:/Krish_New/SLGA/pHc_100_200_EV_N_P_AU_NAT_C_20140801.tif' mode='r'>

In [8]:
site_slga_data

,AVP_000_005,AVP_005_015,AVP_015_030,AVP_030_060,AVP_060_100,AVP_100_200,CLY_000_005,CLY_005_015,CLY_015_030,CLY_030_060,...,SLT_005_015,SLT_030_060,SLT_060_100,SLT_100_200,pHc_000_005,pHc_005_015,pHc_015_030,pHc_030_060,pHc_060_100,pHc_100_200
NSABBS0001,41.250000,32.250000,11.500000,8.250000,9.000000,7.500000,15.750000,16.750000,19.750000,22.500000,...,12.500000,12.250000,11.250000,13.00,5.911349,5.908731,6.090138,6.149799,6.305011,6.503961
NSABBS0002,41.000000,32.750000,12.250000,8.250000,8.250000,6.750000,16.250000,17.500000,22.250000,27.750000,...,13.000000,12.250000,11.250000,13.25,5.641203,5.636680,5.807450,5.846457,6.019695,6.224033
NSABBS0003,8111.000000,8107.000000,8102.000000,8101.833333,8103.666667,8107.000000,10.000000,12.800000,15.000000,18.400000,...,8.000000,8.000000,9.600000,9.60,5.743322,5.829329,6.072671,6.279499,6.439816,6.459643
NSABBS0004,18.333333,13.500000,8.000000,7.333333,9.500000,13.166667,8.833333,11.833333,13.666667,15.666667,...,7.833333,7.833333,9.000000,9.50,5.822774,5.915548,6.172719,6.374738,6.526344,6.539190
NSABBS0005,18.500000,14.000000,7.000000,6.000000,8.166667,10.666667,9.833333,12.833333,15.000000,13.166667,...,7.833333,7.666667,8.833333,9.00,5.784267,5.874176,6.133616,6.367352,6.542438,6.567882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WAGCOO0001,8102.166667,8101.166667,8098.666667,8097.333333,8097.666667,8097.333333,11.200000,12.400000,15.800000,19.799999,...,7.200000,7.800000,7.000000,8.00,5.374317,5.390033,5.489561,5.461819,5.604017,5.700063
WAGCOO0002,7.250000,5.750000,3.500000,2.000000,2.000000,2.000000,8.500000,8.750000,10.500000,11.750000,...,4.250000,4.750000,4.250000,7.00,5.238029,5.247667,5.333941,5.336809,5.485204,5.567737
WAGCOO0004,8.166667,6.666667,3.000000,2.000000,2.000000,1.500000,12.666667,14.333333,19.833334,22.500000,...,9.000000,10.000000,9.666667,8.00,5.944817,5.980247,6.143389,6.322495,6.489493,6.602462
QDASEQ0001,26.250000,20.250000,8.250000,5.250000,3.000000,2.000000,18.000000,19.000000,22.750000,33.000000,...,12.750000,12.000000,12.000000,11.50,4.881130,4.883613,4.936232,4.918678,5.053555,5.174457
SASMDD0013,50.000000,45.750000,6.500000,5.000000,7.000000,5.000000,29.000000,33.250000,35.750000,40.250000,...,13.500000,14.000000,14.500000,11.00,6.700884,6.797203,7.034399,7.452563,7.690821,7.783084

In [9]:
site_slga_data.to_csv('../DATASETS/Soils_and_Landscape_Grid_of_Australia/Output/site_slga_data.csv')

In [10]:
site_slga_data = pd.read_csv('../DATASETS/Soils_and_Landscape_Grid_of_Australia/Output/site_slga_data.csv', index_col = 0)
site_slga_data.head()

,AVP_000_005,AVP_005_015,AVP_015_030,AVP_030_060,AVP_060_100,AVP_100_200,CLY_000_005,CLY_005_015,CLY_015_030,CLY_030_060,...,SLT_005_015,SLT_030_060,SLT_060_100,SLT_100_200,pHc_000_005,pHc_005_015,pHc_015_030,pHc_030_060,pHc_060_100,pHc_100_200
NSABBS0001,41.250000,32.25,11.50,8.250000,9.000000,7.500000,15.750000,16.750000,19.750000,22.500000,...,12.500000,12.250000,11.250000,13.00,5.911349,5.908731,6.090138,6.149799,6.305011,6.503961
NSABBS0002,41.000000,32.75,12.25,8.250000,8.250000,6.750000,16.250000,17.500000,22.250000,27.750000,...,13.000000,12.250000,11.250000,13.25,5.641203,5.636680,5.807450,5.846457,6.019695,6.224033
NSABBS0003,8111.000000,8107.00,8102.00,8101.833333,8103.666667,8107.000000,10.000000,12.800000,15.000000,18.400000,...,8.000000,8.000000,9.600000,9.60,5.743322,5.829330,6.072671,6.279499,6.439817,6.459643
NSABBS0004,18.333333,13.50,8.00,7.333333,9.500000,13.166667,8.833333,11.833333,13.666667,15.666667,...,7.833334,7.833334,9.000000,9.50,5.822774,5.915548,6.172720,6.374738,6.526344,6.539190
NSABBS0005,18.500000,14.00,7.00,6.000000,8.166667,10.666667,9.833333,12.833333,15.000000,13.166667,...,7.833334,7.666666,8.833333,9.00,5.784267,5.874176,6.133616,6.367352,6.542438,6.567882

In [11]:
site_slga_data.describe()

,AVP_000_005,AVP_005_015,AVP_015_030,AVP_030_060,AVP_060_100,AVP_100_200,CLY_000_005,CLY_005_015,CLY_015_030,CLY_030_060,...,SLT_005_015,SLT_030_060,SLT_060_100,SLT_100_200,pHc_000_005,pHc_005_015,pHc_015_030,pHc_030_060,pHc_060_100,pHc_100_200
count,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,...,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000,735.000000
mean,477.787075,474.876153,467.465949,464.900454,464.941686,464.036772,14.384786,15.684525,18.514473,21.539735,...,8.790038,9.766660,10.302519,9.097546,5.830250,5.863826,5.995051,6.175933,6.364264,6.504147
std,2281.246296,2281.328156,2281.664208,2281.770500,2281.763311,2281.871466,8.254217,8.726719,9.493558,9.992866,...,3.606832,3.573926,3.665888,2.147363,0.788421,0.819078,0.859615,0.904185,0.916193,0.928617
min,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,3.000000,...,1.333333,2.000000,1.750000,2.000000,4.012408,3.962643,3.993627,4.000769,4.066658,3.986110
25%,9.500000,7.750000,4.000000,2.000000,2.000000,2.000000,8.625000,9.166667,11.250000,13.500000,...,6.000000,7.250000,8.000000,7.708333,5.286911,5.287163,5.378211,5.520352,5.738644,5.914299
50%,16.000000,13.000000,6.000000,3.500000,3.000000,3.000000,12.750000,14.250000,18.000000,21.500000,...,8.500000,10.000000,10.250000,9.166667,5.725190,5.759634,5.890887,6.091668,6.304082,6.513766
75%,22.750000,18.666667,8.000000,5.000000,5.791667,4.750000,17.166666,19.266667,23.000000,27.000000,...,11.333333,12.000000,12.500000,10.527777,6.462095,6.515261,6.672994,6.909127,7.109219,7.260044
max,24298.000000,24296.500000,24292.500000,24291.000000,24291.000000,24291.000000,49.000000,49.500000,52.666668,54.166668,...,21.500000,21.500000,24.750000,15.500000,7.709297,7.764076,7.975222,8.198814,8.355891,8.402822

In [12]:
site_slga_data['PTO_060_100']

NSABBS0001    0.029717
NSABBS0002    0.026921
NSABBS0003    0.014331
NSABBS0004    0.015015
NSABBS0005    0.014192
                ...
WAGCOO0001    0.007904
WAGCOO0002    0.008260
WAGCOO0004    0.012333
QDASEQ0001    0.024861
SASMDD0013    0.023339
Name: PTO_060_100, Length: 735, dtype: float64

In [13]:
#AVP_060_100
site_slga_data['AVP_060_100']

NSABBS0001       9.000000
NSABBS0002       8.250000
NSABBS0003    8103.666667
NSABBS0004       9.500000
NSABBS0005       8.166667
                 ...
WAGCOO0001    8097.666667
WAGCOO0002       2.000000
WAGCOO0004       2.000000
QDASEQ0001       3.000000
SASMDD0013       7.000000
Name: AVP_060_100, Length: 735, dtype: float64

In [14]:
groups = []
for i in site_slga_data.index:
    groups.append(i[:6])
    
site_slga_data_1 = site_slga_data.copy()
site_slga_data_1['group'] = groups