# Create Lagged Variables for $T_{mean}$

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Get a site
site_subset = pd.read_csv("../DATASETS/Sites_Subset_20231010/ausplots_site_info/sites_subset.csv")
site_subset.head()

,Unnamed: 0,site_unique,site_location_name,established_date,description,bioregion_name,landform_pattern,landform_element,site_slope,site_aspect,...,pit_marker_location_method,soil_observation_type,a_s_c,plot_is_100m_by_100m,plot_is_aligned_to_grid,plot_is_permanently_marked,latitude,longitude,point,state
0,189,WAAPIL0003-57601,WAAPIL0003,2015-08-30T11:01:10,Millstream Chichester National Park. 200m east...,PIL,RIS,HSL,2.0,270.0,...,DGPS,P,NaN,True,True,True,-21.541103,117.057006,SW,WA
1,226,NSABHC0023-57099,NSABHC0023,2014-04-21T00:00:00,Langawirra Station. 11.3km north of homestead....,BHC,PLA,PLA,0.0,NaN,...,NaN,P,NaN,True,True,True,-31.343950,142.136553,SW,NSW
2,300,TCATCH0006-58807,TCATCH0006,2020-02-06T15:29:07,"Liawenee Moor. 5.4km north west of Miena, 7.5k...",TCH,PLA,PLA,1.0,9.0,...,TABLET,P,4 FE? AA AF? CD BFMOU (revised edition),True,True,True,-41.965805,146.652027,SW,TAS
3,331,WAAGAS0002-58421,WAAGAS0002,2016-08-08T15:32:20,"South Side of track, 10.1km west of abandoned ...",GAS,FLO,FAN,0.0,NaN,...,GPS,PA,NaN,True,True,True,-23.384700,120.479139,SW,WA
4,364,NSAMDD0014-56963,NSAMDD0014,2014-06-04T00:00:00,Scotia Sanctuary. 8kms north of homestead 131 ...,MDD,DUN,DUS,1.0,1.0,...,GPS,P,NaN,True,True,True,-33.167939,141.191817,SW,NSW

In [4]:
## Lets try WAAPIL0003
site_location_name = 'WAAPIL0003'
file_name = f'{site_location_name}_1987_2022.csv'
tmin = pd.read_csv(f'../DATASETS/Climate_Gridded/tmin/{file_name}', usecols = ['tmin', 'time'], parse_dates = ['time']).copy() # tmin
tmax = pd.read_csv(f'../DATASETS/Climate_Gridded/tmax/{file_name}', usecols = ['tmax', 'time'], parse_dates = ['time']).copy() # tmax

In [5]:
climate_data = tmin.copy().merge(tmax, left_on = 'time', right_on = 'time')
climate_data = climate_data.sort_values('time')

In [7]:
climate_data['tmean'] = (climate_data['tmin'] + climate_data['tmax'])/2

In [8]:
climate_data

            tmin       time       tmax      tmean
0      26.447266 1987-01-01  43.898438  35.172852
1      26.397461 1987-01-02  44.227539  35.312500
2      28.107422 1987-01-03  41.057617  34.582520
3      26.827148 1987-01-04  40.477539  33.652344
4      24.216797 1987-01-05  39.887695  32.052246
...          ...        ...        ...        ...
13144  25.958984 2022-12-27  38.904297  32.431641
13145  26.848633 2022-12-28  41.154297  34.001465
13146  27.838867 2022-12-29  40.503906  34.171387
13147  28.678711 2022-12-30  44.234375  36.456543
13148  24.228516 2022-12-31  42.463867  33.346191

[13149 rows x 4 columns]